name: Test

on:
  workflow_dispatch: {}
  push: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9"]
        torch: ["1.8", "1.9", "1.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Package
        run: |
          pip install torch~=${{ matrix.torch }}.0
          pip install .[test]

      - name: Test
        run: |
          NUMBA_DISABLE_JIT=1 pytest --cov --cov-report term-missing --cov-fail-under 90 tests/
          black --check .
          isort --diff .
          flake8 .
